### PR TITLE
Fix FONA Tx contention

### PR DESCRIPTION
**Pull request by riosil**
This is my proposed solution to the communication issue from the FONA to the ATmega. I believe this is an important step before branching to further development.

It fixes the contention between the FONA Tx and SPI SS pins, as described in the forum ('Firmware stuff'). With this, messages from the FONA can be observed over serial USB via the ATmega. Should I also include a photo/description of the hardware mod here?

I also changed the name of _main.ino_, because it makes development a little easier, no more _main_ sub-folder. I hope that's OK and doesn't confuse anyone (otherwise I'll change back).

_Best wishes for the Wednesday launch.
Steve_

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@jhaupt

- Why is a 2 year old PR still open?

- Why did you link to it in the README
  instead of just accepting this PR?

**Comment by riosil** [comment]
My firmware developed rapidly after this PR, so that accepting it could have led to a 'rabbit hole' of further work. Soon after raising this PR, my humble opinion was Justine's time would be better spent on the next gen Rotary Un-Smartphone... and the next gen is looking amazing! I should have closed this long ago.

**Comment by ElectronicsArchiver** [comment]
I see, well not like accepting PRs takes that much time but sure.

In that case I'd recommend uncoupling your repo, since you don't seem to plan on merging your fork from your own initiative anymore and make it a distinguished project.

**Comment by ElectronicsArchiver** [comment]
@riosil Heres the link to GitHubs chatbot that would do this : https://support.github.com/request/fork ( Detach Option )

**Comment by riosil** [comment]
Request submitted - thank you

**Pull request closed without merging**
